title: Jacqueline Zawada # your name (or website title) here
logo: "/images/photo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science • Data Visualization • Statistical Analysis
  <br><br>
  Dedicated Data Analyst and Applied Statistician. Recent master’s graduate with strong expertise in R, Python, Power BI and advanced statistical analysis tools.
  <br><br>
  <a href="https://www.linkedin.com/in/jacqueline-zawada-aa624427b">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
